export const ap = [
  {
    name: "Amit Datta Shuvo 1",
    id: 1,
    dateAdded: "18/10/2023",
    sDate: "23/10/2023",
    sTime: "Morning 10am",
    note: "Aliquam erat volutpat. Suspendisse euismod id risus ut rutrum. Cras sed tellus id quam lacinia ullamcorper ut ut lectus. Fusce imperdiet dui nibh, vel egestas mi vulputate at. Vestibulum convallis dignissim erat ut maximus. Aenean aliquet ut neque sed tincidunt. Nullam et leo ac arcu tincidunt porttitor.",
    category: "Electrician",
  },
  {
    name: "Anik Datta",
    id: 2,
    dateAdded: "19/10/2023",
    sDate: "24/10/2023",
    sTime: "Noon 12pm",
    note: "Aliquam erat volutpat. Suspendisse euismod id risus ut rutrum. Cras sed tellus id quam lacinia ullamcorper ut ut lectus. Fusce imperdiet dui nibh, vel egestas mi vulputate at. Vestibulum convallis dignissim erat ut maximus. Aenean aliquet ut neque sed tincidunt. Nullam et leo ac arcu tincidunt porttitor.",
    category: "Painter",
  },
  {
    name: "Mahbub Shahriar",
    id: 3,
    dateAdded: "19/10/2023",
    sDate: "24/10/2023",
    sTime: "Noon 12pm",
    note: "Aliquam erat volutpat. Suspendisse euismod id risus ut rutrum. Cras sed tellus id quam lacinia ullamcorper ut ut lectus. Fusce imperdiet dui nibh, vel egestas mi vulputate at. Vestibulum convallis dignissim erat ut maximus. Aenean aliquet ut neque sed tincidunt. Nullam et leo ac arcu tincidunt porttitor.",
    category: "Painter",
  },
  {
    name: "Irfan Ali",
    id: 4,
    dateAdded: "19/10/2023",
    sDate: "24/10/2023",
    sTime: "Noon 12pm",
    note: "Aliquam erat volutpat. Suspendisse euismod id risus ut rutrum. Cras sed tellus id quam lacinia ullamcorper ut ut lectus. Fusce imperdiet dui nibh, vel egestas mi vulputate at. Vestibulum convallis dignissim erat ut maximus. Aenean aliquet ut neque sed tincidunt. Nullam et leo ac arcu tincidunt porttitor.",
    category: "Painter",
  },
  {
    name: "Anik Datta",
    id: 5,
    dateAdded: "19/10/2023",
    sDate: "24/10/2023",
    sTime: "Noon 12pm",
    note: "Aliquam erat volutpat. Suspendisse euismod id risus ut rutrum. Cras sed tellus id quam lacinia ullamcorper ut ut lectus. Fusce imperdiet dui nibh, vel egestas mi vulputate at. Vestibulum convallis dignissim erat ut maximus. Aenean aliquet ut neque sed tincidunt. Nullam et leo ac arcu tincidunt porttitor.",
    category: "Painter",
  },
];
