export const persons = [
  {
    user_id: 1,
    user_img: "./user1.png",
    user_fullname: "Aminul Haque",
    user_name: "aminul01",
    user_email: "aminul01@gmail.com",
    user_pass: "G^wHe3O&Tl67",
    user_dob: "01/16/1999",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 11,
    user_verficationStatus: "25%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 14,
    user_reviews: [
      {
        reviewId: 1,
        reviewer: "Mr. Rahman 1",
        reviewerImg: "./user2.png",
        review: "Great electrician service by user 1.",
        date: "August 15, 2022",
      },
      {
        reviewId: 2,
        reviewer: "Mr. Rahman 1",
        reviewerImg: "./user1.png",
        review: "Great electrician.",
        date: "August 15, 2022",
      },
      {
        reviewId: 2,
        reviewer: "Mr. Rahman 1",
        reviewerImg: "./user1.png",
        review: "Great electrician.",
        date: "August 15, 2022",
      },
      {
        reviewId: 2,
        reviewer: "Mr. Rahman 1",
        reviewerImg: "./user1.png",
        review: "Great electrician.",
        date: "August 15, 2022",
      },
    ],
  },
  {
    user_id: 2,
    user_img: "./user2.png",
    user_fullname: "Farhan Ahmed",
    user_name: "farhan02",
    user_email: "farhan02@gmail.com",
    user_pass: "PZXLD9eBy0NK",
    user_dob: "06/25/1995",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 20,
    user_verficationStatus: "0%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 13,
    user_reviews: [
      {
        reviewId: 2,
        reviewer: "Mr. Rahman 2",
        reviewerImg: "./user3.png",
        review: "Great electrician service by user 2.",
        date: "August 11, 2023",
      },
    ],
  },
  {
    user_id: 3,
    user_img: "./user3.png",
    user_fullname: "Rafiqul Islam",
    user_name: "rafiqul03",
    user_email: "rafiqul03@gmail.com",
    user_pass: "gJ$J6I!POnZnt^u",
    user_dob: "09/08/1979",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2022,
    user_hireCount: 22,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 5,
    user_reviews: [
      {
        reviewId: 3,
        reviewer: "Mr. Rahman",
        reviewerImg: "./user4.png",
        review: "Great cleaning service.",
        date: "August 22, 2023",
      },
    ],
  },
  {
    user_id: 4,
    user_img: "./user4.png",
    user_fullname: "Sohel Mia",
    user_name: "sohel04",
    user_email: "sohel04@gmail.com",
    user_pass: "*tCe*Ygv1oGBP",
    user_dob: "12/04/2001",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "Mohakhali, Dhaka",
    user_regYear: 2022,
    user_hireCount: 32,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 6,
    user_reviews: [
      {
        reviewId: 4,
        reviewer: "Mr. Rahman",
        reviewerImg: "./user5.png",
        review: "Great cleaning service service by user 4.",
        date: "August 7, 2022",
      },
      {
        reviewId: 2,
        reviewer: "Mr. Rahman",
        reviewerImg: "./user3.png",
        review: "Great cleaning service.",
        date: "August 7, 2022",
      },
      {
        reviewId: 2,
        reviewer: "Mr. Rahman",
        reviewerImg: "./user3.png",
        review: "Great cleaning service.",
        date: "August 7, 2022",
      },
    ],
  },
  {
    user_id: 5,
    user_img: "./user5.png",
    user_fullname: "Mohammad Rahman",
    user_name: "mohammad05",
    user_email: "mohammad05@gmail.com",
    user_pass: "Y0U48cE!bp",
    user_dob: "12/14/1999",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 21,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 5,
    user_reviews: [
      {
        reviewId: 5,
        reviewer: "Mr. Rahman 5",
        reviewerImg: "./user6.png",
        review: "Great painting service service by user 5.",
        date: "August 4, 2022",
      },
    ],
  },
  {
    user_id: 6,
    user_img: "./user6.png",
    user_fullname: "Sohel Mia",
    user_name: "sohel06",
    user_email: "sohel06@gmail.com",
    user_pass: "xLWFrhbIq5AuSu1e",
    user_dob: "03/25/1990",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2022,
    user_hireCount: 43,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 2,
    user_reviews: [
      {
        reviewId: 6,
        reviewer: "Mr. Rahman 6",
        reviewerImg: "./user7.png",
        review: "Great cleaning service service by user 6.",
        date: "August 27, 2022",
      },
    ],
  },
  {
    user_id: 7,
    user_img: "./user7.png",
    user_fullname: "Shahin Ahmed",
    user_name: "shahin07",
    user_email: "shahin07@gmail.com",
    user_pass: "NcptQ7w2X",
    user_dob: "12/25/1999",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "South Badda, Dhaka",
    user_regYear: 2022,
    user_hireCount: 49,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 12,
    user_reviews: [
      {
        reviewId: 7,
        reviewer: "Mr. Rahman 7",
        reviewerImg: "./user8.png",
        review: "Great plumbing service service by user 7.",
        date: "August 26, 2022",
      },
    ],
  },
  {
    user_id: 8,
    user_img: "./user8.png",
    user_fullname: "Sohel Mia",
    user_name: "sohel08",
    user_email: "sohel08@gmail.com",
    user_pass: "tvTgWA#K",
    user_dob: "07/04/1982",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 28,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 6,
    user_reviews: [
      {
        reviewId: 8,
        reviewer: "Mr. Rahman 8",
        reviewerImg: "./user9.png",
        review: "Great plumbing service service by user 8.",
        date: "August 2, 2023",
      },
    ],
  },
  {
    user_id: 9,
    user_img: "./user9.png",
    user_fullname: "Tariqul Haque",
    user_name: "tariqul09",
    user_email: "tariqul09@gmail.com",
    user_pass: "Bf%q04jl",
    user_dob: "02/26/2000",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Premium",
    user_location: "Mohakhali, Dhaka",
    user_regYear: 2022,
    user_hireCount: 7,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 15,
    user_reviews: [
      {
        reviewId: 9,
        reviewer: "Mr. Rahman 9",
        reviewerImg: "./user10.png",
        review: "Great painting service service by user 9.",
        date: "August 4, 2022",
      },
    ],
  },
  {
    user_id: 10,
    user_img: "./user10.png",
    user_fullname: "Rafiqul Islam",
    user_name: "rafiqul10",
    user_email: "rafiqul10@gmail.com",
    user_pass: "4F6Q*S0e",
    user_dob: "04/13/1996",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "South Badda, Dhaka",
    user_regYear: 2022,
    user_hireCount: 1,
    user_verficationStatus: "75%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 10,
    user_reviews: [
      {
        reviewId: 10,
        reviewer: "Mr. Rahman 10",
        reviewerImg: "./user11.png",
        review: "Great electrician service by user 10.",
        date: "August 17, 2023",
      },
    ],
  },
  {
    user_id: 11,
    user_img: "./user11.png",
    user_fullname: "Tariqul Haque",
    user_name: "tariqul11",
    user_email: "tariqul11@gmail.com",
    user_pass: "kKsiA1xWZ*xB",
    user_dob: "07/27/2004",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "South Badda, Dhaka",
    user_regYear: 2023,
    user_hireCount: 29,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 2,
    user_reviews: [
      {
        reviewId: 11,
        reviewer: "Mr. Rahman 11",
        reviewerImg: "./user12.png",
        review: "Great plumbing service service by user 11.",
        date: "August 7, 2023",
      },
    ],
  },
  {
    user_id: 12,
    user_img: "./user12.png",
    user_fullname: "Mohammad Rahman",
    user_name: "mohammad12",
    user_email: "mohammad12@gmail.com",
    user_pass: "MULex&0ecafyiBac",
    user_dob: "11/22/1991",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2022,
    user_hireCount: 16,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 5,
    user_reviews: [
      {
        reviewId: 12,
        reviewer: "Mr. Rahman 12",
        reviewerImg: "./user13.png",
        review: "Great painting service service by user 12.",
        date: "August 4, 2023",
      },
    ],
  },
  {
    user_id: 13,
    user_img: "./user13.png",
    user_fullname: "Aminul Haque",
    user_name: "aminul13",
    user_email: "aminul13@gmail.com",
    user_pass: "56ZuwuoTGU9b",
    user_dob: "07/06/1997",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "Mohakhali, Dhaka",
    user_regYear: 2023,
    user_hireCount: 25,
    user_verficationStatus: "50%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 12,
    user_reviews: [
      {
        reviewId: 13,
        reviewer: "Mr. Rahman 13",
        reviewerImg: "./user14.png",
        review: "Great electrician service by user 13.",
        date: "August 8, 2022",
      },
    ],
  },
  {
    user_id: 14,
    user_img: "./user14.png",
    user_fullname: "Sajid Ali",
    user_name: "sajid14",
    user_email: "sajid14@gmail.com",
    user_pass: "c*SSoUyX&%ye7u",
    user_dob: "02/12/1980",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2023,
    user_hireCount: 37,
    user_verficationStatus: "75%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 6,
    user_reviews: [
      {
        reviewId: 14,
        reviewer: "Mr. Rahman 14",
        reviewerImg: "./user15.png",
        review: "Great electrician service by user 14.",
        date: "August 12, 2022",
      },
    ],
  },
  {
    user_id: 15,
    user_img: "./user15.png",
    user_fullname: "Ashraf Uddin",
    user_name: "ashraf15",
    user_email: "ashraf15@gmail.com",
    user_pass: "8qL%Jv*xoT",
    user_dob: "05/20/1993",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 6,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 11,
    user_reviews: [
      {
        reviewId: 15,
        reviewer: "Mr. Rahman 15",
        reviewerImg: "./user16.png",
        review: "Great cleaning service service by user 15.",
        date: "August 22, 2022",
      },
    ],
  },
  {
    user_id: 16,
    user_img: "./user16.png",
    user_fullname: "Rafiqul Islam",
    user_name: "rafiqul16",
    user_email: "rafiqul16@gmail.com",
    user_pass: "%Pxvmv2kF824smH%",
    user_dob: "12/23/1979",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Regular",
    user_location: "South Badda, Dhaka",
    user_regYear: 2022,
    user_hireCount: 2,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 9,
    user_reviews: [
      {
        reviewId: 16,
        reviewer: "Mr. Rahman 16",
        reviewerImg: "./user17.png",
        review: "Great plumbing service service by user 16.",
        date: "August 6, 2022",
      },
    ],
  },
  {
    user_id: 17,
    user_img: "./user17.png",
    user_fullname: "Shahid Islam",
    user_name: "shahid17",
    user_email: "shahid17@gmail.com",
    user_pass: "ew3VkecRuwDy@D",
    user_dob: "05/22/1976",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "Uttara, Dhaka",
    user_regYear: 2023,
    user_hireCount: 37,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 13,
    user_reviews: [
      {
        reviewId: 17,
        reviewer: "Mr. Rahman 17",
        reviewerImg: "./user18.png",
        review: "Great cleaning service service by user 17.",
        date: "August 29, 2023",
      },
    ],
  },
  {
    user_id: 18,
    user_img: "./user18.png",
    user_fullname: "Ashraf Uddin",
    user_name: "ashraf18",
    user_email: "ashraf18@gmail.com",
    user_pass: "7%oyLeerRFw&C",
    user_dob: "06/04/1992",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 17,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 5,
    user_reviews: [
      {
        reviewId: 18,
        reviewer: "Mr. Rahman 18",
        reviewerImg: "./user19.png",
        review: "Great plumbing service service by user 18.",
        date: "August 16, 2022",
      },
    ],
  },
  {
    user_id: 19,
    user_img: "./user19.png",
    user_fullname: "Sohel Mia",
    user_name: "sohel19",
    user_email: "sohel19@gmail.com",
    user_pass: "kDvX#v6zikCU5",
    user_dob: "01/22/2000",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "Mohakhali, Dhaka",
    user_regYear: 2022,
    user_hireCount: 11,
    user_verficationStatus: "0%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 1,
    user_reviews: [
      {
        reviewId: 19,
        reviewer: "Mr. Rahman 19",
        reviewerImg: "./user20.png",
        review: "Great electrician service by user 19.",
        date: "August 10, 2022",
      },
    ],
  },
  {
    user_id: 20,
    user_img: "./user20.png",
    user_fullname: "Ahmed Khan",
    user_name: "ahmed20",
    user_email: "ahmed20@gmail.com",
    user_pass: "S@eMxM6i",
    user_dob: "12/28/1995",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2022,
    user_hireCount: 49,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 3,
    user_reviews: [
      {
        reviewId: 20,
        reviewer: "Mr. Rahman 20",
        reviewerImg: "./user21.png",
        review: "Great painting service service by user 20.",
        date: "August 16, 2022",
      },
    ],
  },
  {
    user_id: 21,
    user_img: "./user21.png",
    user_fullname: "Nasir Uddin",
    user_name: "nasir21",
    user_email: "nasir21@gmail.com",
    user_pass: "9mnZje##EgIWa*Cb",
    user_dob: "04/16/1977",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2022,
    user_hireCount: 31,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 3,
    user_reviews: [
      {
        reviewId: 21,
        reviewer: "Mr. Rahman 21",
        reviewerImg: "./user22.png",
        review: "Great painting service service by user 21.",
        date: "August 19, 2023",
      },
    ],
  },
  {
    user_id: 22,
    user_img: "./user22.png",
    user_fullname: "Saifullah Akbar",
    user_name: "saifullah22",
    user_email: "saifullah22@gmail.com",
    user_pass: "1lTfh#9SD#",
    user_dob: "03/28/1988",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 47,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 3,
    user_reviews: [
      {
        reviewId: 22,
        reviewer: "Mr. Rahman 22",
        reviewerImg: "./user23.png",
        review: "Great painting service service by user 22.",
        date: "August 17, 2023",
      },
    ],
  },
  {
    user_id: 23,
    user_img: "./user23.png",
    user_fullname: "Rafiqul Islam",
    user_name: "rafiqul23",
    user_email: "rafiqul23@gmail.com",
    user_pass: "t^XYMu!j",
    user_dob: "05/06/2000",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2023,
    user_hireCount: 42,
    user_verficationStatus: "25%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 2,
    user_reviews: [
      {
        reviewId: 23,
        reviewer: "Mr. Rahman 23",
        reviewerImg: "./user24.png",
        review: "Great electrician service by user 23.",
        date: "August 14, 2022",
      },
    ],
  },
  {
    user_id: 24,
    user_img: "./user24.png",
    user_fullname: "Sajid Ali",
    user_name: "sajid24",
    user_email: "sajid24@gmail.com",
    user_pass: "iidD7FcNg",
    user_dob: "02/05/2003",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2022,
    user_hireCount: 37,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 24,
        reviewer: "Mr. Rahman 24",
        reviewerImg: "./user25.png",
        review: "Great cleaning service service by user 24.",
        date: "August 4, 2022",
      },
    ],
  },
  {
    user_id: 25,
    user_img: "./user25.png",
    user_fullname: "Imran Hossain",
    user_name: "imran25",
    user_email: "imran25@gmail.com",
    user_pass: "P%r2jjz1AuNFBlR",
    user_dob: "10/04/1999",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "Mohakhali, Dhaka",
    user_regYear: 2023,
    user_hireCount: 8,
    user_verficationStatus: "75%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 1,
    user_reviews: [
      {
        reviewId: 25,
        reviewer: "Mr. Rahman 25",
        reviewerImg: "./user26.png",
        review: "Great electrician service by user 25.",
        date: "August 18, 2022",
      },
    ],
  },
  {
    user_id: 26,
    user_img: "./user26.png",
    user_fullname: "Tariqul Haque",
    user_name: "tariqul26",
    user_email: "tariqul26@gmail.com",
    user_pass: "UdBvkB0qz4",
    user_dob: "01/04/1972",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 44,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 1,
    user_reviews: [
      {
        reviewId: 26,
        reviewer: "Mr. Rahman 26",
        reviewerImg: "./user27.png",
        review: "Great plumbing service service by user 26.",
        date: "August 19, 2023",
      },
    ],
  },
  {
    user_id: 27,
    user_img: "./user27.png",
    user_fullname: "Nasir Uddin",
    user_name: "nasir27",
    user_email: "nasir27@gmail.com",
    user_pass: "UV5m@$wo",
    user_dob: "05/14/2000",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 24,
    user_verficationStatus: "50%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 15,
    user_reviews: [
      {
        reviewId: 27,
        reviewer: "Mr. Rahman 27",
        reviewerImg: "./user28.png",
        review: "Great electrician service by user 27.",
        date: "August 30, 2022",
      },
    ],
  },
  {
    user_id: 28,
    user_img: "./user28.png",
    user_fullname: "Shahin Ahmed",
    user_name: "shahin28",
    user_email: "shahin28@gmail.com",
    user_pass: "uqY$zfZzOR@LHv",
    user_dob: "09/19/1975",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Regular",
    user_location: "Mohakhali, Dhaka",
    user_regYear: 2022,
    user_hireCount: 46,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 28,
        reviewer: "Mr. Rahman 28",
        reviewerImg: "./user29.png",
        review: "Great plumbing service service by user 28.",
        date: "August 20, 2022",
      },
    ],
  },
  {
    user_id: 29,
    user_img: "./user29.png",
    user_fullname: "Mohammad Rahman",
    user_name: "mohammad29",
    user_email: "mohammad29@gmail.com",
    user_pass: "yKsRJSeGm",
    user_dob: "07/01/2001",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 11,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 10,
    user_reviews: [
      {
        reviewId: 29,
        reviewer: "Mr. Rahman 29",
        reviewerImg: "./user30.png",
        review: "Great painting service service by user 29.",
        date: "August 30, 2022",
      },
    ],
  },
  {
    user_id: 30,
    user_img: "./user30.png",
    user_fullname: "Abu Bakar Siddique",
    user_name: "abu30",
    user_email: "abu30@gmail.com",
    user_pass: "sb2o3h3uNgd",
    user_dob: "12/23/2004",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 14,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 6,
    user_reviews: [
      {
        reviewId: 30,
        reviewer: "Mr. Rahman 30",
        reviewerImg: "./user31.png",
        review: "Great plumbing service service by user 30.",
        date: "August 1, 2023",
      },
    ],
  },
  {
    user_id: 31,
    user_img: "./user31.png",
    user_fullname: "Sajid Ali",
    user_name: "sajid31",
    user_email: "sajid31@gmail.com",
    user_pass: "UxtHuvG#D&l1",
    user_dob: "05/16/2003",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 21,
    user_verficationStatus: "50%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 9,
    user_reviews: [
      {
        reviewId: 31,
        reviewer: "Mr. Rahman 31",
        reviewerImg: "./user32.png",
        review: "Great electrician service by user 31.",
        date: "August 26, 2023",
      },
    ],
  },
  {
    user_id: 32,
    user_img: "./user32.png",
    user_fullname: "Sajid Ali",
    user_name: "sajid32",
    user_email: "sajid32@gmail.com",
    user_pass: "4i^1Nl5t!CS",
    user_dob: "04/07/2003",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2023,
    user_hireCount: 39,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 12,
    user_reviews: [
      {
        reviewId: 32,
        reviewer: "Mr. Rahman 32",
        reviewerImg: "./user33.png",
        review: "Great plumbing service service by user 32.",
        date: "August 27, 2022",
      },
    ],
  },
  {
    user_id: 33,
    user_img: "./user33.png",
    user_fullname: "Ariful Islam",
    user_name: "ariful33",
    user_email: "ariful33@gmail.com",
    user_pass: "mVg*lRYtw@",
    user_dob: "04/22/1984",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2023,
    user_hireCount: 27,
    user_verficationStatus: "0%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 14,
    user_reviews: [
      {
        reviewId: 33,
        reviewer: "Mr. Rahman 33",
        reviewerImg: "./user34.png",
        review: "Great electrician service by user 33.",
        date: "August 28, 2023",
      },
    ],
  },
  {
    user_id: 34,
    user_img: "./user34.png",
    user_fullname: "Rafiqul Islam",
    user_name: "rafiqul34",
    user_email: "rafiqul34@gmail.com",
    user_pass: "legem4DJTI6rcTG",
    user_dob: "05/22/2003",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "Mohakhali, Dhaka",
    user_regYear: 2022,
    user_hireCount: 30,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 8,
    user_reviews: [
      {
        reviewId: 34,
        reviewer: "Mr. Rahman 34",
        reviewerImg: "./user35.png",
        review: "Great cleaning service service by user 34.",
        date: "August 21, 2023",
      },
    ],
  },
  {
    user_id: 35,
    user_img: "./user35.png",
    user_fullname: "Ariful Islam",
    user_name: "ariful35",
    user_email: "ariful35@gmail.com",
    user_pass: "3DVLv#CXc9Rvm1",
    user_dob: "04/13/2004",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Premium",
    user_location: "Mohakhali, Dhaka",
    user_regYear: 2023,
    user_hireCount: 41,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 1,
    user_reviews: [
      {
        reviewId: 35,
        reviewer: "Mr. Rahman 35",
        reviewerImg: "./user36.png",
        review: "Great painting service service by user 35.",
        date: "August 17, 2023",
      },
    ],
  },
  {
    user_id: 36,
    user_img: "./user36.png",
    user_fullname: "Ashraf Uddin",
    user_name: "ashraf36",
    user_email: "ashraf36@gmail.com",
    user_pass: "6Q#L!njOdZ",
    user_dob: "12/24/1983",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "South Badda, Dhaka",
    user_regYear: 2023,
    user_hireCount: 5,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 12,
    user_reviews: [
      {
        reviewId: 36,
        reviewer: "Mr. Rahman 36",
        reviewerImg: "./user37.png",
        review: "Great plumbing service service by user 36.",
        date: "August 21, 2023",
      },
    ],
  },
  {
    user_id: 37,
    user_img: "./user37.png",
    user_fullname: "Ariful Islam",
    user_name: "ariful37",
    user_email: "ariful37@gmail.com",
    user_pass: "W7CAn&pBj",
    user_dob: "11/18/1993",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2022,
    user_hireCount: 36,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 15,
    user_reviews: [
      {
        reviewId: 37,
        reviewer: "Mr. Rahman 37",
        reviewerImg: "./user38.png",
        review: "Great painting service service by user 37.",
        date: "August 14, 2022",
      },
    ],
  },
  {
    user_id: 38,
    user_img: "./user38.png",
    user_fullname: "Sajid Ali",
    user_name: "sajid38",
    user_email: "sajid38@gmail.com",
    user_pass: "wnoIj!GiJBlE",
    user_dob: "12/21/1973",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2023,
    user_hireCount: 48,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 13,
    user_reviews: [
      {
        reviewId: 38,
        reviewer: "Mr. Rahman 38",
        reviewerImg: "./user39.png",
        review: "Great painting service service by user 38.",
        date: "August 9, 2022",
      },
    ],
  },
  {
    user_id: 39,
    user_img: "./user39.png",
    user_fullname: "Imran Hossain",
    user_name: "imran39",
    user_email: "imran39@gmail.com",
    user_pass: "7bf74@3AO",
    user_dob: "12/12/2002",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Premium",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2023,
    user_hireCount: 35,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 39,
        reviewer: "Mr. Rahman 39",
        reviewerImg: "./user40.png",
        review: "Great painting service service by user 39.",
        date: "August 16, 2023",
      },
    ],
  },
  {
    user_id: 40,
    user_img: "./user40.png",
    user_fullname: "Farhan Ahmed",
    user_name: "farhan40",
    user_email: "farhan40@gmail.com",
    user_pass: "EHoeD0T3DyEejvG",
    user_dob: "01/02/2004",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 23,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 9,
    user_reviews: [
      {
        reviewId: 40,
        reviewer: "Mr. Rahman 40",
        reviewerImg: "./user41.png",
        review: "Great cleaning service service by user 40.",
        date: "August 5, 2022",
      },
    ],
  },
  {
    user_id: 41,
    user_img: "./user41.png",
    user_fullname: "Imran Hossain",
    user_name: "imran41",
    user_email: "imran41@gmail.com",
    user_pass: "^QUYB6qxBK",
    user_dob: "11/26/1977",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2022,
    user_hireCount: 19,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 41,
        reviewer: "Mr. Rahman 41",
        reviewerImg: "./user42.png",
        review: "Great cleaning service service by user 41.",
        date: "August 22, 2023",
      },
    ],
  },
  {
    user_id: 42,
    user_img: "./user42.png",
    user_fullname: "Sajid Ali",
    user_name: "sajid42",
    user_email: "sajid42@gmail.com",
    user_pass: "56L1KGpM",
    user_dob: "03/02/1986",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Regular",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 3,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 3,
    user_reviews: [
      {
        reviewId: 42,
        reviewer: "Mr. Rahman 42",
        reviewerImg: "./user43.png",
        review: "Great plumbing service service by user 42.",
        date: "August 20, 2023",
      },
    ],
  },
  {
    user_id: 43,
    user_img: "./user43.png",
    user_fullname: "Shahin Ahmed",
    user_name: "shahin43",
    user_email: "shahin43@gmail.com",
    user_pass: "I2^D7euy15bZf",
    user_dob: "09/04/1984",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 50,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 1,
    user_reviews: [
      {
        reviewId: 43,
        reviewer: "Mr. Rahman 43",
        reviewerImg: "./user44.png",
        review: "Great plumbing service service by user 43.",
        date: "August 26, 2023",
      },
    ],
  },
  {
    user_id: 44,
    user_img: "./user44.png",
    user_fullname: "Abu Bakar Siddique",
    user_name: "abu44",
    user_email: "abu44@gmail.com",
    user_pass: "Q!9pLN9XKQr",
    user_dob: "08/06/1977",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 3,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 10,
    user_reviews: [
      {
        reviewId: 44,
        reviewer: "Mr. Rahman 44",
        reviewerImg: "./user45.png",
        review: "Great cleaning service service by user 44.",
        date: "August 18, 2022",
      },
    ],
  },
  {
    user_id: 45,
    user_img: "./user45.png",
    user_fullname: "Faisal Ahmed",
    user_name: "faisal45",
    user_email: "faisal45@gmail.com",
    user_pass: "Jp1i4SUEGq8%",
    user_dob: "12/16/1973",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2022,
    user_hireCount: 40,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 1,
    user_reviews: [
      {
        reviewId: 45,
        reviewer: "Mr. Rahman 45",
        reviewerImg: "./user46.png",
        review: "Great cleaning service service by user 45.",
        date: "August 27, 2023",
      },
    ],
  },
  {
    user_id: 46,
    user_img: "./user46.png",
    user_fullname: "Farhan Ahmed",
    user_name: "farhan46",
    user_email: "farhan46@gmail.com",
    user_pass: "1cnAM*KG",
    user_dob: "07/11/1984",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2023,
    user_hireCount: 41,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 46,
        reviewer: "Mr. Rahman 46",
        reviewerImg: "./user47.png",
        review: "Great painting service service by user 46.",
        date: "August 28, 2023",
      },
    ],
  },
  {
    user_id: 47,
    user_img: "./user47.png",
    user_fullname: "Rafiqul Islam",
    user_name: "rafiqul47",
    user_email: "rafiqul47@gmail.com",
    user_pass: "glK*%!XvNQ^jq",
    user_dob: "06/15/1992",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 15,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 12,
    user_reviews: [
      {
        reviewId: 47,
        reviewer: "Mr. Rahman 47",
        reviewerImg: "./user48.png",
        review: "Great cleaning service service by user 47.",
        date: "August 24, 2022",
      },
    ],
  },
  {
    user_id: 48,
    user_img: "./user48.png",
    user_fullname: "Aminul Haque",
    user_name: "aminul48",
    user_email: "aminul48@gmail.com",
    user_pass: "KoxW6ziMJVNE0UB",
    user_dob: "04/12/1991",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 3,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 13,
    user_reviews: [
      {
        reviewId: 48,
        reviewer: "Mr. Rahman 48",
        reviewerImg: "./user49.png",
        review: "Great cleaning service service by user 48.",
        date: "August 29, 2022",
      },
    ],
  },
  {
    user_id: 49,
    user_img: "./user49.png",
    user_fullname: "Sohel Mia",
    user_name: "sohel49",
    user_email: "sohel49@gmail.com",
    user_pass: "%*6K^uyTr@C^49",
    user_dob: "09/06/1982",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 8,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 9,
    user_reviews: [
      {
        reviewId: 49,
        reviewer: "Mr. Rahman 49",
        reviewerImg: "./user50.png",
        review: "Great cleaning service service by user 49.",
        date: "August 20, 2022",
      },
    ],
  },
  {
    user_id: 50,
    user_img: "./user50.png",
    user_fullname: "Faisal Ahmed",
    user_name: "faisal50",
    user_email: "faisal50@gmail.com",
    user_pass: "Fs!FsWOl80I6",
    user_dob: "08/26/1983",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Premium",
    user_location: "South Badda, Dhaka",
    user_regYear: 2022,
    user_hireCount: 23,
    user_verficationStatus: "75%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 50,
        reviewer: "Mr. Rahman 50",
        reviewerImg: "./user51.png",
        review: "Great electrician service by user 50.",
        date: "August 1, 2022",
      },
    ],
  },
  {
    user_id: 51,
    user_img: "./user51.png",
    user_fullname: "Mohammad Rahman",
    user_name: "mohammad51",
    user_email: "mohammad51@gmail.com",
    user_pass: "dhoVl4CgByGR4zh",
    user_dob: "05/12/1981",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "South Badda, Dhaka",
    user_regYear: 2023,
    user_hireCount: 2,
    user_verficationStatus: "75%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 5,
    user_reviews: [
      {
        reviewId: 51,
        reviewer: "Mr. Rahman 51",
        reviewerImg: "./user52.png",
        review: "Great electrician service by user 51.",
        date: "August 31, 2022",
      },
    ],
  },
  {
    user_id: 52,
    user_img: "./user52.png",
    user_fullname: "Saifullah Akbar",
    user_name: "saifullah52",
    user_email: "saifullah52@gmail.com",
    user_pass: "HoA0b2VV*j%UF6",
    user_dob: "11/25/2001",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2022,
    user_hireCount: 11,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 7,
    user_reviews: [
      {
        reviewId: 52,
        reviewer: "Mr. Rahman 52",
        reviewerImg: "./user53.png",
        review: "Great painting service service by user 52.",
        date: "August 21, 2022",
      },
    ],
  },
  {
    user_id: 53,
    user_img: "./user53.png",
    user_fullname: "Ahmed Khan",
    user_name: "ahmed53",
    user_email: "ahmed53@gmail.com",
    user_pass: "%b#tnV7Cj",
    user_dob: "07/15/1991",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2023,
    user_hireCount: 29,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 8,
    user_reviews: [
      {
        reviewId: 53,
        reviewer: "Mr. Rahman 53",
        reviewerImg: "./user54.png",
        review: "Great painting service service by user 53.",
        date: "August 14, 2022",
      },
    ],
  },
  {
    user_id: 54,
    user_img: "./user54.png",
    user_fullname: "Saifullah Akbar",
    user_name: "saifullah54",
    user_email: "saifullah54@gmail.com",
    user_pass: "bOLSBeyZl",
    user_dob: "12/19/1993",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Regular",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2023,
    user_hireCount: 48,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 1,
    user_reviews: [
      {
        reviewId: 54,
        reviewer: "Mr. Rahman 54",
        reviewerImg: "./user55.png",
        review: "Great plumbing service service by user 54.",
        date: "August 30, 2023",
      },
    ],
  },
  {
    user_id: 55,
    user_img: "./user55.png",
    user_fullname: "Mohammad Rahman",
    user_name: "mohammad55",
    user_email: "mohammad55@gmail.com",
    user_pass: "mrlRNxViquAGU",
    user_dob: "11/12/2005",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2022,
    user_hireCount: 46,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 13,
    user_reviews: [
      {
        reviewId: 55,
        reviewer: "Mr. Rahman 55",
        reviewerImg: "./user56.png",
        review: "Great plumbing service service by user 55.",
        date: "August 12, 2022",
      },
    ],
  },
  {
    user_id: 56,
    user_img: "./user56.png",
    user_fullname: "Sajid Ali",
    user_name: "sajid56",
    user_email: "sajid56@gmail.com",
    user_pass: "1Cih$3QXrj4@Z",
    user_dob: "06/28/1996",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2023,
    user_hireCount: 47,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 11,
    user_reviews: [
      {
        reviewId: 56,
        reviewer: "Mr. Rahman 56",
        reviewerImg: "./user57.png",
        review: "Great plumbing service service by user 56.",
        date: "August 30, 2023",
      },
    ],
  },
  {
    user_id: 57,
    user_img: "./user57.png",
    user_fullname: "Faisal Ahmed",
    user_name: "faisal57",
    user_email: "faisal57@gmail.com",
    user_pass: "vXX0Qi1kf",
    user_dob: "11/06/1988",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 50,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 3,
    user_reviews: [
      {
        reviewId: 57,
        reviewer: "Mr. Rahman 57",
        reviewerImg: "./user58.png",
        review: "Great cleaning service service by user 57.",
        date: "August 17, 2023",
      },
    ],
  },
  {
    user_id: 58,
    user_img: "./user58.png",
    user_fullname: "Ariful Islam",
    user_name: "ariful58",
    user_email: "ariful58@gmail.com",
    user_pass: "SbfpXxiVy",
    user_dob: "12/20/1986",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "South Badda, Dhaka",
    user_regYear: 2022,
    user_hireCount: 45,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 8,
    user_reviews: [
      {
        reviewId: 58,
        reviewer: "Mr. Rahman 58",
        reviewerImg: "./user59.png",
        review: "Great painting service service by user 58.",
        date: "August 28, 2022",
      },
    ],
  },
  {
    user_id: 59,
    user_img: "./user59.png",
    user_fullname: "Tariqul Haque",
    user_name: "tariqul59",
    user_email: "tariqul59@gmail.com",
    user_pass: "xBVazTP*UoE",
    user_dob: "01/19/2003",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "South Badda, Dhaka",
    user_regYear: 2023,
    user_hireCount: 7,
    user_verficationStatus: "50%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 9,
    user_reviews: [
      {
        reviewId: 59,
        reviewer: "Mr. Rahman 59",
        reviewerImg: "./user60.png",
        review: "Great electrician service by user 59.",
        date: "August 21, 2023",
      },
    ],
  },
  {
    user_id: 60,
    user_img: "./user60.png",
    user_fullname: "Anwar Chowdhury",
    user_name: "anwar60",
    user_email: "anwar60@gmail.com",
    user_pass: "yX0ETty2Cy#X4na",
    user_dob: "03/08/1985",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 24,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 60,
        reviewer: "Mr. Rahman 60",
        reviewerImg: "./user61.png",
        review: "Great cleaning service service by user 60.",
        date: "August 29, 2023",
      },
    ],
  },
  {
    user_id: 61,
    user_img: "./user61.png",
    user_fullname: "Ashraf Uddin",
    user_name: "ashraf61",
    user_email: "ashraf61@gmail.com",
    user_pass: "p83R6#Qqfe",
    user_dob: "09/17/1997",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "South Badda, Dhaka",
    user_regYear: 2023,
    user_hireCount: 18,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 61,
        reviewer: "Mr. Rahman 61",
        reviewerImg: "./user62.png",
        review: "Great plumbing service service by user 61.",
        date: "August 14, 2023",
      },
    ],
  },
  {
    user_id: 62,
    user_img: "./user62.png",
    user_fullname: "Jahangir Khan",
    user_name: "jahangir62",
    user_email: "jahangir62@gmail.com",
    user_pass: "d*OoTTOOpj*",
    user_dob: "05/02/1973",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2022,
    user_hireCount: 4,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 3,
    user_reviews: [
      {
        reviewId: 62,
        reviewer: "Mr. Rahman 62",
        reviewerImg: "./user63.png",
        review: "Great cleaning service service by user 62.",
        date: "August 23, 2023",
      },
    ],
  },
  {
    user_id: 63,
    user_img: "./user63.png",
    user_fullname: "Rafiqul Islam",
    user_name: "rafiqul63",
    user_email: "rafiqul63@gmail.com",
    user_pass: "s#72fU%twl#Bu7&",
    user_dob: "08/22/1989",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "Mohakhali, Dhaka",
    user_regYear: 2022,
    user_hireCount: 4,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 14,
    user_reviews: [
      {
        reviewId: 63,
        reviewer: "Mr. Rahman 63",
        reviewerImg: "./user64.png",
        review: "Great cleaning service service by user 63.",
        date: "August 5, 2022",
      },
    ],
  },
  {
    user_id: 64,
    user_img: "./user64.png",
    user_fullname: "Shahin Ahmed",
    user_name: "shahin64",
    user_email: "shahin64@gmail.com",
    user_pass: "rPNy43TghkUlt",
    user_dob: "10/19/1985",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Regular",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 20,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 8,
    user_reviews: [
      {
        reviewId: 64,
        reviewer: "Mr. Rahman 64",
        reviewerImg: "./user65.png",
        review: "Great plumbing service service by user 64.",
        date: "August 27, 2023",
      },
    ],
  },
  {
    user_id: 65,
    user_img: "./user65.png",
    user_fullname: "Aminul Haque",
    user_name: "aminul65",
    user_email: "aminul65@gmail.com",
    user_pass: "*o%6aWU2pgyDhIDd",
    user_dob: "12/13/1987",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2023,
    user_hireCount: 47,
    user_verficationStatus: "25%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 3,
    user_reviews: [
      {
        reviewId: 65,
        reviewer: "Mr. Rahman 65",
        reviewerImg: "./user66.png",
        review: "Great electrician service by user 65.",
        date: "August 12, 2022",
      },
    ],
  },
  {
    user_id: 66,
    user_img: "./user66.png",
    user_fullname: "Shahid Islam",
    user_name: "shahid66",
    user_email: "shahid66@gmail.com",
    user_pass: "nXJEQzJoU5aV4v7",
    user_dob: "03/03/2005",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 13,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 66,
        reviewer: "Mr. Rahman 66",
        reviewerImg: "./user67.png",
        review: "Great plumbing service service by user 66.",
        date: "August 19, 2023",
      },
    ],
  },
  {
    user_id: 67,
    user_img: "./user67.png",
    user_fullname: "Saifullah Akbar",
    user_name: "saifullah67",
    user_email: "saifullah67@gmail.com",
    user_pass: "1*fW*RPFLbTeM^yW",
    user_dob: "08/25/1989",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "South Badda, Dhaka",
    user_regYear: 2023,
    user_hireCount: 4,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 2,
    user_reviews: [
      {
        reviewId: 67,
        reviewer: "Mr. Rahman 67",
        reviewerImg: "./user68.png",
        review: "Great cleaning service service by user 67.",
        date: "August 23, 2022",
      },
    ],
  },
  {
    user_id: 68,
    user_img: "./user68.png",
    user_fullname: "Sohel Mia",
    user_name: "sohel68",
    user_email: "sohel68@gmail.com",
    user_pass: "#8yXC@O&BM16oy",
    user_dob: "06/18/1973",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Regular",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2022,
    user_hireCount: 1,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 7,
    user_reviews: [
      {
        reviewId: 68,
        reviewer: "Mr. Rahman 68",
        reviewerImg: "./user69.png",
        review: "Great plumbing service service by user 68.",
        date: "August 25, 2023",
      },
    ],
  },
  {
    user_id: 69,
    user_img: "./user69.png",
    user_fullname: "Ahmed Khan",
    user_name: "ahmed69",
    user_email: "ahmed69@gmail.com",
    user_pass: "7VAi#x7jDUCY^k8",
    user_dob: "07/06/1987",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2023,
    user_hireCount: 39,
    user_verficationStatus: "75%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 10,
    user_reviews: [
      {
        reviewId: 69,
        reviewer: "Mr. Rahman 69",
        reviewerImg: "./user70.png",
        review: "Great electrician service by user 69.",
        date: "August 21, 2022",
      },
    ],
  },
  {
    user_id: 70,
    user_img: "./user70.png",
    user_fullname: "Shahid Islam",
    user_name: "shahid70",
    user_email: "shahid70@gmail.com",
    user_pass: "QS#kMW!S1qVv3",
    user_dob: "11/04/1978",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2023,
    user_hireCount: 18,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 70,
        reviewer: "Mr. Rahman 70",
        reviewerImg: "./user71.png",
        review: "Great painting service service by user 70.",
        date: "August 20, 2023",
      },
    ],
  },
  {
    user_id: 71,
    user_img: "./user71.png",
    user_fullname: "Sohel Mia",
    user_name: "sohel71",
    user_email: "sohel71@gmail.com",
    user_pass: "tN!EeNJ!^rvu2%0x",
    user_dob: "02/17/1972",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Premium",
    user_location: "South Badda, Dhaka",
    user_regYear: 2023,
    user_hireCount: 44,
    user_verficationStatus: "0%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 10,
    user_reviews: [
      {
        reviewId: 71,
        reviewer: "Mr. Rahman 71",
        reviewerImg: "./user72.png",
        review: "Great electrician service by user 71.",
        date: "August 5, 2023",
      },
    ],
  },
  {
    user_id: 72,
    user_img: "./user72.png",
    user_fullname: "Abu Bakar Siddique",
    user_name: "abu72",
    user_email: "abu72@gmail.com",
    user_pass: "aCwlkYqwU7",
    user_dob: "09/06/1987",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Regular",
    user_location: "Uttara, Dhaka",
    user_regYear: 2023,
    user_hireCount: 19,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 9,
    user_reviews: [
      {
        reviewId: 72,
        reviewer: "Mr. Rahman 72",
        reviewerImg: "./user73.png",
        review: "Great plumbing service service by user 72.",
        date: "August 10, 2022",
      },
    ],
  },
  {
    user_id: 73,
    user_img: "./user73.png",
    user_fullname: "Ashraf Uddin",
    user_name: "ashraf73",
    user_email: "ashraf73@gmail.com",
    user_pass: "pTq86oIRv@sr%td",
    user_dob: "02/25/2000",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "South Badda, Dhaka",
    user_regYear: 2022,
    user_hireCount: 24,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 9,
    user_reviews: [
      {
        reviewId: 73,
        reviewer: "Mr. Rahman 73",
        reviewerImg: "./user74.png",
        review: "Great cleaning service service by user 73.",
        date: "August 11, 2022",
      },
    ],
  },
  {
    user_id: 74,
    user_img: "./user74.png",
    user_fullname: "Ashraf Uddin",
    user_name: "ashraf74",
    user_email: "ashraf74@gmail.com",
    user_pass: "QAfO*b1co!j^pQYx",
    user_dob: "01/13/1980",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Regular",
    user_location: "Mohakhali, Dhaka",
    user_regYear: 2023,
    user_hireCount: 3,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 74,
        reviewer: "Mr. Rahman 74",
        reviewerImg: "./user75.png",
        review: "Great plumbing service service by user 74.",
        date: "August 14, 2023",
      },
    ],
  },
  {
    user_id: 75,
    user_img: "./user75.png",
    user_fullname: "Imran Hossain",
    user_name: "imran75",
    user_email: "imran75@gmail.com",
    user_pass: "BfZMhhKfg^$3a",
    user_dob: "11/14/1999",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 14,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 13,
    user_reviews: [
      {
        reviewId: 75,
        reviewer: "Mr. Rahman 75",
        reviewerImg: "./user76.png",
        review: "Great painting service service by user 75.",
        date: "August 11, 2022",
      },
    ],
  },
  {
    user_id: 76,
    user_img: "./user76.png",
    user_fullname: "Ashraf Uddin",
    user_name: "ashraf76",
    user_email: "ashraf76@gmail.com",
    user_pass: "K@0mZd7Z0CZ12ZTH",
    user_dob: "05/28/1971",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "South Badda, Dhaka",
    user_regYear: 2022,
    user_hireCount: 45,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 76,
        reviewer: "Mr. Rahman 76",
        reviewerImg: "./user77.png",
        review: "Great plumbing service service by user 76.",
        date: "August 17, 2022",
      },
    ],
  },
  {
    user_id: 77,
    user_img: "./user77.png",
    user_fullname: "Farhan Ahmed",
    user_name: "farhan77",
    user_email: "farhan77@gmail.com",
    user_pass: "2q%lhNB#6Q1k",
    user_dob: "03/19/1980",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 39,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 5,
    user_reviews: [
      {
        reviewId: 77,
        reviewer: "Mr. Rahman 77",
        reviewerImg: "./user78.png",
        review: "Great painting service service by user 77.",
        date: "August 28, 2022",
      },
    ],
  },
  {
    user_id: 78,
    user_img: "./user78.png",
    user_fullname: "Aminul Haque",
    user_name: "aminul78",
    user_email: "aminul78@gmail.com",
    user_pass: "ca9DU%PDwBplA",
    user_dob: "03/24/1982",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2022,
    user_hireCount: 31,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 10,
    user_reviews: [
      {
        reviewId: 78,
        reviewer: "Mr. Rahman 78",
        reviewerImg: "./user79.png",
        review: "Great plumbing service service by user 78.",
        date: "August 18, 2023",
      },
    ],
  },
  {
    user_id: 79,
    user_img: "./user79.png",
    user_fullname: "Nasir Uddin",
    user_name: "nasir79",
    user_email: "nasir79@gmail.com",
    user_pass: "w^aNtaE*cJaQGwr$",
    user_dob: "02/27/1980",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 8,
    user_verficationStatus: "25%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 3,
    user_reviews: [
      {
        reviewId: 79,
        reviewer: "Mr. Rahman 79",
        reviewerImg: "./user80.png",
        review: "Great electrician service by user 79.",
        date: "August 27, 2023",
      },
    ],
  },
  {
    user_id: 80,
    user_img: "./user80.png",
    user_fullname: "Aminul Haque",
    user_name: "aminul80",
    user_email: "aminul80@gmail.com",
    user_pass: "X*Qa3QX74U&Hii",
    user_dob: "10/18/1981",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 1,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 9,
    user_reviews: [
      {
        reviewId: 80,
        reviewer: "Mr. Rahman 80",
        reviewerImg: "./user81.png",
        review: "Great painting service service by user 80.",
        date: "August 15, 2022",
      },
    ],
  },
  {
    user_id: 81,
    user_img: "./user81.png",
    user_fullname: "Abu Bakar Siddique",
    user_name: "abu81",
    user_email: "abu81@gmail.com",
    user_pass: "6fT#jQuqQQ",
    user_dob: "02/25/1971",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "South Badda, Dhaka",
    user_regYear: 2022,
    user_hireCount: 49,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 13,
    user_reviews: [
      {
        reviewId: 81,
        reviewer: "Mr. Rahman 81",
        reviewerImg: "./user82.png",
        review: "Great cleaning service service by user 81.",
        date: "August 29, 2022",
      },
    ],
  },
  {
    user_id: 82,
    user_img: "./user82.png",
    user_fullname: "Anwar Chowdhury",
    user_name: "anwar82",
    user_email: "anwar82@gmail.com",
    user_pass: "yodpEaJXFoxB1s",
    user_dob: "05/16/1976",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2022,
    user_hireCount: 42,
    user_verficationStatus: "75%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 6,
    user_reviews: [
      {
        reviewId: 82,
        reviewer: "Mr. Rahman 82",
        reviewerImg: "./user83.png",
        review: "Great electrician service by user 82.",
        date: "August 25, 2023",
      },
    ],
  },
  {
    user_id: 83,
    user_img: "./user83.png",
    user_fullname: "Aminul Haque",
    user_name: "aminul83",
    user_email: "aminul83@gmail.com",
    user_pass: "*fXmdkBk$7",
    user_dob: "06/25/1987",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 19,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 83,
        reviewer: "Mr. Rahman 83",
        reviewerImg: "./user84.png",
        review: "Great painting service service by user 83.",
        date: "August 27, 2022",
      },
    ],
  },
  {
    user_id: 84,
    user_img: "./user84.png",
    user_fullname: "Shahid Islam",
    user_name: "shahid84",
    user_email: "shahid84@gmail.com",
    user_pass: "uVAq3D^R$nh6$Hv4",
    user_dob: "12/06/1988",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Regular",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2023,
    user_hireCount: 29,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 10,
    user_reviews: [
      {
        reviewId: 84,
        reviewer: "Mr. Rahman 84",
        reviewerImg: "./user85.png",
        review: "Great cleaning service service by user 84.",
        date: "August 3, 2022",
      },
    ],
  },
  {
    user_id: 85,
    user_img: "./user85.png",
    user_fullname: "Aminul Haque",
    user_name: "aminul85",
    user_email: "aminul85@gmail.com",
    user_pass: "Ja7cU204Gcxf",
    user_dob: "08/21/1970",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2023,
    user_hireCount: 5,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 11,
    user_reviews: [
      {
        reviewId: 85,
        reviewer: "Mr. Rahman 85",
        reviewerImg: "./user86.png",
        review: "Great cleaning service service by user 85.",
        date: "August 29, 2023",
      },
    ],
  },
  {
    user_id: 86,
    user_img: "./user86.png",
    user_fullname: "Imran Hossain",
    user_name: "imran86",
    user_email: "imran86@gmail.com",
    user_pass: "9XHY&7eV$P",
    user_dob: "02/03/2005",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "Mohakhali, Dhaka",
    user_regYear: 2022,
    user_hireCount: 11,
    user_verficationStatus: "25%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 11,
    user_reviews: [
      {
        reviewId: 86,
        reviewer: "Mr. Rahman 86",
        reviewerImg: "./user87.png",
        review: "Great electrician service by user 86.",
        date: "August 14, 2022",
      },
    ],
  },
  {
    user_id: 87,
    user_img: "./user87.png",
    user_fullname: "Nasir Uddin",
    user_name: "nasir87",
    user_email: "nasir87@gmail.com",
    user_pass: "#O88YcC*oCS6WZ",
    user_dob: "07/25/1994",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "South Badda, Dhaka",
    user_regYear: 2023,
    user_hireCount: 19,
    user_verficationStatus: "0%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 10,
    user_reviews: [
      {
        reviewId: 87,
        reviewer: "Mr. Rahman 87",
        reviewerImg: "./user88.png",
        review: "Great electrician service by user 87.",
        date: "August 8, 2022",
      },
    ],
  },
  {
    user_id: 88,
    user_img: "./user88.png",
    user_fullname: "Sohel Mia",
    user_name: "sohel88",
    user_email: "sohel88@gmail.com",
    user_pass: "a238!PHk",
    user_dob: "11/11/1990",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 38,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 3,
    user_reviews: [
      {
        reviewId: 88,
        reviewer: "Mr. Rahman 88",
        reviewerImg: "./user89.png",
        review: "Great plumbing service service by user 88.",
        date: "August 18, 2022",
      },
    ],
  },
  {
    user_id: 89,
    user_img: "./user89.png",
    user_fullname: "Imran Hossain",
    user_name: "imran89",
    user_email: "imran89@gmail.com",
    user_pass: "NJu97GsGr7AQhiw",
    user_dob: "10/12/1983",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2023,
    user_hireCount: 50,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 14,
    user_reviews: [
      {
        reviewId: 89,
        reviewer: "Mr. Rahman 89",
        reviewerImg: "./user90.png",
        review: "Great cleaning service service by user 89.",
        date: "August 2, 2023",
      },
    ],
  },
  {
    user_id: 90,
    user_img: "./user90.png",
    user_fullname: "Shahin Ahmed",
    user_name: "shahin90",
    user_email: "shahin90@gmail.com",
    user_pass: "VGlHP@n9grm4",
    user_dob: "11/19/1976",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Regular",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 48,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 9,
    user_reviews: [
      {
        reviewId: 90,
        reviewer: "Mr. Rahman 90",
        reviewerImg: "./user91.png",
        review: "Great plumbing service service by user 90.",
        date: "August 1, 2022",
      },
    ],
  },
  {
    user_id: 91,
    user_img: "./user91.png",
    user_fullname: "Jahangir Khan",
    user_name: "jahangir91",
    user_email: "jahangir91@gmail.com",
    user_pass: "kLbqgrdtVyY",
    user_dob: "06/26/1971",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2023,
    user_hireCount: 40,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 13,
    user_reviews: [
      {
        reviewId: 91,
        reviewer: "Mr. Rahman 91",
        reviewerImg: "./user92.png",
        review: "Great painting service service by user 91.",
        date: "August 18, 2022",
      },
    ],
  },
  {
    user_id: 92,
    user_img: "./user92.png",
    user_fullname: "Saifullah Akbar",
    user_name: "saifullah92",
    user_email: "saifullah92@gmail.com",
    user_pass: "VYnqF@bvaKiZPfL",
    user_dob: "03/03/1976",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Regular",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2022,
    user_hireCount: 5,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 7,
    user_reviews: [
      {
        reviewId: 92,
        reviewer: "Mr. Rahman 92",
        reviewerImg: "./user93.png",
        review: "Great plumbing service service by user 92.",
        date: "August 30, 2023",
      },
    ],
  },
  {
    user_id: 93,
    user_img: "./user93.png",
    user_fullname: "Anwar Chowdhury",
    user_name: "anwar93",
    user_email: "anwar93@gmail.com",
    user_pass: "NwEZoNPvZIEl",
    user_dob: "05/18/1992",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Premium",
    user_location: "Mirpur, Dhaka",
    user_regYear: 2022,
    user_hireCount: 1,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 3,
    user_reviews: [
      {
        reviewId: 93,
        reviewer: "Mr. Rahman 93",
        reviewerImg: "./user94.png",
        review: "Great plumbing service service by user 93.",
        date: "August 12, 2023",
      },
    ],
  },
  {
    user_id: 94,
    user_img: "./user94.png",
    user_fullname: "Jahangir Khan",
    user_name: "jahangir94",
    user_email: "jahangir94@gmail.com",
    user_pass: "$YEP2ROGhNUuE4",
    user_dob: "10/07/1974",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Premium",
    user_location: "South Badda, Dhaka",
    user_regYear: 2022,
    user_hireCount: 9,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 2,
    user_reviews: [
      {
        reviewId: 94,
        reviewer: "Mr. Rahman 94",
        reviewerImg: "./user95.png",
        review: "Great painting service service by user 94.",
        date: "August 17, 2022",
      },
    ],
  },
  {
    user_id: 95,
    user_img: "./user95.png",
    user_fullname: "Kamrul Hasan",
    user_name: "kamrul95",
    user_email: "kamrul95@gmail.com",
    user_pass: "EMoug4gG1u*",
    user_dob: "05/18/1981",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Plumber",
    user_status: "Regular",
    user_location: "South Badda, Dhaka",
    user_regYear: 2023,
    user_hireCount: 46,
    user_verficationStatus: "0%",
    user_serviceDetails:
      "I'm a pro plumbing service offering top-notch service.",
    user_respondTime: 1,
    user_reviews: [
      {
        reviewId: 95,
        reviewer: "Mr. Rahman 95",
        reviewerImg: "./user96.png",
        review: "Great plumbing service service by user 95.",
        date: "August 9, 2023",
      },
    ],
  },
  {
    user_id: 96,
    user_img: "./user96.png",
    user_fullname: "Sajid Ali",
    user_name: "sajid96",
    user_email: "sajid96@gmail.com",
    user_pass: "o&6*hI4ZpkCWuG",
    user_dob: "11/01/1994",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2022,
    user_hireCount: 6,
    user_verficationStatus: "25%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 6,
    user_reviews: [
      {
        reviewId: 96,
        reviewer: "Mr. Rahman 96",
        reviewerImg: "./user97.png",
        review: "Great cleaning service service by user 96.",
        date: "August 7, 2022",
      },
    ],
  },
  {
    user_id: 97,
    user_img: "./user97.png",
    user_fullname: "Farhan Ahmed",
    user_name: "farhan97",
    user_email: "farhan97@gmail.com",
    user_pass: "c3G&%RWDch*",
    user_dob: "11/19/1998",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Regular",
    user_location: "Uttara, Dhaka",
    user_regYear: 2023,
    user_hireCount: 22,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 5,
    user_reviews: [
      {
        reviewId: 97,
        reviewer: "Mr. Rahman 97",
        reviewerImg: "./user98.png",
        review: "Great painting service service by user 97.",
        date: "August 5, 2023",
      },
    ],
  },
  {
    user_id: 98,
    user_img: "./user98.png",
    user_fullname: "Saifullah Akbar",
    user_name: "saifullah98",
    user_email: "saifullah98@gmail.com",
    user_pass: "Q7EeuHl#$rvMBXL",
    user_dob: "08/18/1977",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Painting Service",
    user_status: "Premium",
    user_location: "Uttara, Dhaka",
    user_regYear: 2023,
    user_hireCount: 13,
    user_verficationStatus: "75%",
    user_serviceDetails:
      "I'm a pro painting service offering top-notch service.",
    user_respondTime: 8,
    user_reviews: [
      {
        reviewId: 98,
        reviewer: "Mr. Rahman 98",
        reviewerImg: "./user99.png",
        review: "Great painting service service by user 98.",
        date: "August 25, 2022",
      },
    ],
  },
  {
    user_id: 99,
    user_img: "./user99.png",
    user_fullname: "Faisal Ahmed",
    user_name: "faisal99",
    user_email: "faisal99@gmail.com",
    user_pass: "zKqZN$hoO@4xQ",
    user_dob: "02/11/1998",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Electrician",
    user_status: "Regular",
    user_location: "South Badda, Dhaka",
    user_regYear: 2022,
    user_hireCount: 40,
    user_verficationStatus: "75%",
    user_serviceDetails: "I'm a pro electrician offering top-notch service.",
    user_respondTime: 5,
    user_reviews: [
      {
        reviewId: 99,
        reviewer: "Mr. Rahman 99",
        reviewerImg: "./user1.png",
        review: "Great electrician service by user 99.",
        date: "August 26, 2022",
      },
    ],
  },
  {
    user_id: 100,
    user_img: "./user100.png",
    user_fullname: "Farhan Ahmed",
    user_name: "farhan100",
    user_email: "farhan100@gmail.com",
    user_pass: "!sKQ@aP3j",
    user_dob: "11/10/1990",
    user_gender: "Male",
    user_type: "Service Provider",
    user_category: "Cleaning Service",
    user_status: "Premium",
    user_location: "Gulshan, Dhaka",
    user_regYear: 2022,
    user_hireCount: 13,
    user_verficationStatus: "50%",
    user_serviceDetails:
      "I'm a pro cleaning service offering top-notch service.",
    user_respondTime: 4,
    user_reviews: [
      {
        reviewId: 100,
        reviewer: "Mr. Rahman 100",
        reviewerImg: "./user2.png",
        review: "Great cleaning service service by user 100.",
        date: "August 17, 2022",
      },
    ],
  },
];
